#!/usr/bin/env python3
# Converts data/test_vectors/stage1_conv/{config.json,*.bin} into a C header of static byte
# arrays, since Vitis bare-metal firmware has no filesystem to load the .bin files from.
# Regenerate whenever scripts/generate_stage1_vectors.py produces a new test vector.
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def format_byte_array(name: str, data: bytes, values_per_line: int = 20) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(data), values_per_line):
        chunk = data[i : i + values_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--vector-dir", type=Path,
        default=REPO_ROOT / "data" / "test_vectors" / "stage1_conv",
    )
    parser.add_argument(
        "--output", type=Path,
        default=REPO_ROOT / "firmware" / "test" / "generated" / "stage1_test_vector.h",
    )
    args = parser.parse_args()

    config = json.loads((args.vector_dir / "config.json").read_text())
    weight = (args.vector_dir / "weight.bin").read_bytes()
    bias = (args.vector_dir / "bias.bin").read_bytes()
    input_ = (args.vector_dir / "input.bin").read_bytes()
    expected_output = (args.vector_dir / "expected_output.bin").read_bytes()

    assert len(weight) == config["weight_bytes"]
    assert len(bias) == config["bias_bytes"]
    assert len(input_) == config["input_bytes"]
    assert len(expected_output) == config["output_bytes"]

    args.output.parent.mkdir(parents=True, exist_ok=True)

    body = f"""/* Generated by scripts/generate_stage1_c_header.py from
 * {args.vector_dir.relative_to(REPO_ROOT)} -- do not edit by hand.
 *
 * §13.1 canonical stage-1 single-convolution test vector, embedded as byte arrays
 * because bare-metal firmware has no filesystem to load the .bin files from.
 */
#ifndef STAGE1_TEST_VECTOR_H
#define STAGE1_TEST_VECTOR_H

#include <stdint.h>

#define STAGE1_INPUT_HEIGHT  {config["input_height"]}
#define STAGE1_INPUT_WIDTH   {config["input_width"]}
#define STAGE1_IN_CHANNELS   {config["in_channels"]}
#define STAGE1_OUT_CHANNELS  {config["out_channels"]}
#define STAGE1_KERNEL_SIZE   {config["kernel_size"]}
#define STAGE1_STRIDE        {config["stride"]}
#define STAGE1_PADDING       {config["padding"]}
#define STAGE1_RELU_ENABLE   {1 if config["relu_enable"] else 0}
#define STAGE1_MULTIPLIER_M  {config["multiplier_m"]}
#define STAGE1_SHIFT_N       {config["shift_n"]}

#define STAGE1_WEIGHT_BYTES  {config["weight_bytes"]}
#define STAGE1_BIAS_BYTES    {config["bias_bytes"]}
#define STAGE1_INPUT_BYTES   {config["input_bytes"]}
#define STAGE1_OUTPUT_BYTES  {config["output_bytes"]}

{format_byte_array("stage1_weight", weight)}

{format_byte_array("stage1_bias", bias)}

{format_byte_array("stage1_input", input_)}

{format_byte_array("stage1_expected_output", expected_output)}

#endif /* STAGE1_TEST_VECTOR_H */
"""
    args.output.write_text(body)
    print(f"wrote {args.output} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
