#!/usr/bin/env python3
# Converts data/test_vectors/stage3_gap_fc/chain/* into a C header of static byte arrays,
# mirroring generate_stage2_c_header.py (bare-metal firmware has no filesystem to load .bin
# files from). Regenerate whenever scripts/generate_stage3_gapfc_vectors.py produces new vectors.
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def format_byte_array(name: str, data: bytes, values_per_line: int = 20) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(data), values_per_line):
        chunk = data[i : i + values_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vector-root", type=Path, default=REPO_ROOT / "data" / "test_vectors")
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    vector_dir = args.vector_root / "stage3_gap_fc" / "chain"
    output = args.output or (
        REPO_ROOT / "firmware" / "test" / "generated" / "stage3_gapfc_test_vector.h"
    )

    gap_config = json.loads((vector_dir / "gap" / "config.json").read_text())
    block_output = (vector_dir / "gap" / "input.bin").read_bytes()
    gap_expected_output = (vector_dir / "gap" / "expected_output.bin").read_bytes()
    assert len(block_output) == gap_config["input_bytes"]
    assert len(gap_expected_output) == gap_config["output_bytes"]

    fc_config = json.loads((vector_dir / "fc" / "config.json").read_text())
    fc_weight = (vector_dir / "fc" / "weight.bin").read_bytes()
    fc_bias = (vector_dir / "fc" / "bias.bin").read_bytes()
    fc_expected_output = (vector_dir / "fc" / "expected_output.bin").read_bytes()
    assert len(fc_weight) == fc_config["weight_bytes"]
    assert len(fc_bias) == fc_config["bias_bytes"]
    assert len(fc_expected_output) == fc_config["output_bytes"]

    # fc's real runtime input is gap's own accelerator output, not embedded separately here
    # (same convention as generate_stage2_c_header.py's conv1->conv2 chaining).
    fc_input_check = (vector_dir / "fc" / "input.bin").read_bytes()
    if fc_input_check != gap_expected_output:
        raise ValueError(
            "fc/input.bin does not match gap/expected_output.bin -- vectors are stale, "
            "regenerate with scripts/generate_stage3_gapfc_vectors.py"
        )

    chain_config = json.loads((vector_dir / "chain_config.json").read_text())

    output.parent.mkdir(parents=True, exist_ok=True)
    prefix = "STAGE3_GAPFC"

    body = f"""/* Generated by scripts/generate_stage3_gapfc_c_header.py from
 * {vector_dir.relative_to(REPO_ROOT)} -- do not edit by hand.
 *
 * GAP -> FC test vector (HW_SW_Interface_v1.4_DRAFT.md §2-§4): stage3_block_output(8x8x64)
 * -> OP_GLOBAL_AVG_POOL -> gap_output(64) -> OP_CONV(kernel=1,H=W=1) [=FC, §3.1] ->
 * fc_output(12, first {chain_config["num_valid_classes"]} bytes valid, rest zero-padded per §3.3).
 * gap_output is not chained from a real 9-block backbone yet (no such thing exists,
 * STAGE3_MASTER_ROADMAP.md §2.2) -- block_output is a synthetic INT8 activation.
 */
#ifndef STAGE3_GAPFC_TEST_VECTOR_H
#define STAGE3_GAPFC_TEST_VECTOR_H

#include <stdint.h>

#define {prefix}_GAP_INPUT_HEIGHT   {gap_config["input_height"]}
#define {prefix}_GAP_INPUT_WIDTH    {gap_config["input_width"]}
#define {prefix}_GAP_IN_CHANNELS    {gap_config["in_channels"]}
#define {prefix}_GAP_OUT_CHANNELS   {gap_config["out_channels"]}
#define {prefix}_GAP_MULTIPLIER_M   {gap_config["multiplier_m"]}
#define {prefix}_GAP_SHIFT_N        {gap_config["shift_n"]}
#define {prefix}_GAP_INPUT_BYTES    {gap_config["input_bytes"]}
#define {prefix}_GAP_OUTPUT_BYTES   {gap_config["output_bytes"]}

#define {prefix}_FC_IN_CHANNELS     {fc_config["in_channels"]}
#define {prefix}_FC_OUT_CHANNELS    {fc_config["out_channels"]}
#define {prefix}_FC_KERNEL_SIZE     {fc_config["kernel_size"]}
#define {prefix}_FC_STRIDE          {fc_config["stride"]}
#define {prefix}_FC_PADDING         {fc_config["padding"]}
#define {prefix}_FC_RELU_ENABLE     {1 if fc_config["relu_enable"] else 0}
#define {prefix}_FC_MULTIPLIER_M    {fc_config["multiplier_m"]}
#define {prefix}_FC_SHIFT_N         {fc_config["shift_n"]}
#define {prefix}_FC_WEIGHT_BYTES    {fc_config["weight_bytes"]}
#define {prefix}_FC_BIAS_BYTES      {fc_config["bias_bytes"]}
#define {prefix}_FC_OUTPUT_BYTES    {fc_config["output_bytes"]}

#define {prefix}_NUM_VALID_CLASSES  {chain_config["num_valid_classes"]}
#define {prefix}_EXPECTED_PREDICTED_CLASS {chain_config["predicted_class"]}

{format_byte_array(f"{prefix.lower()}_block_output", block_output)}

{format_byte_array(f"{prefix.lower()}_gap_expected_output", gap_expected_output)}

{format_byte_array(f"{prefix.lower()}_fc_weight", fc_weight)}

{format_byte_array(f"{prefix.lower()}_fc_bias", fc_bias)}

{format_byte_array(f"{prefix.lower()}_fc_expected_output", fc_expected_output)}

#endif /* STAGE3_GAPFC_TEST_VECTOR_H */
"""

    output.write_text(body)
    print(f"wrote {output} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
