#!/usr/bin/env python3
# Converts data/test_vectors/stage1_conv/{config.json,*.bin} into a C header of static byte
# arrays, since Vitis bare-metal firmware has no filesystem to load the .bin files from.
# Regenerate whenever scripts/generate_stage1_vectors.py produces a new test vector.
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def format_byte_array(name: str, data: bytes, values_per_line: int = 20) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(data), values_per_line):
        chunk = data[i : i + values_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def require_alias(config: dict, old: str, new: str) -> int:
    """Accepts either the firmware-side key (old) or the RTL-side key (new), not both, so a
    config that mixes schemas fails loudly instead of silently picking one (§9)."""
    present = [key for key in (old, new) if key in config]
    if len(present) != 1:
        raise ValueError(f"expected exactly one of {old!r}, {new!r} in config.json, got {present}")
    return int(config[present[0]])


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def verify_manifest(vector_dir: Path, manifest_path: Path, payloads: dict[str, bytes]) -> None:
    """Rejects generation if any binary or the config differs from the jointly approved hashes
    recorded for the selected vector candidate (§9 joint decision gate)."""
    manifest = json.loads(manifest_path.read_text())
    approved = manifest["sha256"]
    for name, data in payloads.items():
        expected = approved.get(name)
        if expected is None:
            raise ValueError(f"approved manifest has no sha256 entry for {name!r}")
        actual = sha256_hex(data)
        if actual != expected:
            raise ValueError(f"SHA-256 mismatch for {name}: expected {expected}, got {actual}")

    config_sha = sha256_hex((vector_dir / "config.json").read_bytes())
    expected_config_sha = approved.get("config.json")
    if expected_config_sha is None:
        raise ValueError("approved manifest has no sha256 entry for config.json")
    if config_sha != expected_config_sha:
        raise ValueError(
            f"SHA-256 mismatch for config.json: expected {expected_config_sha}, got {config_sha}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--vector-dir", type=Path,
        default=REPO_ROOT / "data" / "test_vectors" / "stage1_conv",
    )
    parser.add_argument(
        "--output", type=Path,
        default=REPO_ROOT / "firmware" / "test" / "generated" / "stage1_test_vector.h",
    )
    parser.add_argument(
        "--approved-manifest", type=Path, default=None,
        help=(
            "path to a jointly-approved {\"sha256\": {file: hash, ...}} manifest for --vector-dir; "
            "if omitted, no provenance check is performed (development-only default, not for the "
            "first hardware bring-up run — see FIRMWARE_INTEGRATION_PATCH_PROPOSAL.md §9)"
        ),
    )
    args = parser.parse_args()

    config = json.loads((args.vector_dir / "config.json").read_text())
    weight = (args.vector_dir / "weight.bin").read_bytes()
    bias = (args.vector_dir / "bias.bin").read_bytes()
    input_ = (args.vector_dir / "input.bin").read_bytes()
    expected_output = (args.vector_dir / "expected_output.bin").read_bytes()

    assert len(weight) == config["weight_bytes"]
    assert len(bias) == config["bias_bytes"]
    assert len(input_) == config["input_bytes"]
    assert len(expected_output) == config["output_bytes"]

    multiplier_m = require_alias(config, "multiplier_m", "multiplier")
    shift_n = require_alias(config, "shift_n", "shift")

    if args.approved_manifest is not None:
        verify_manifest(
            args.vector_dir, args.approved_manifest,
            {
                "weight.bin": weight, "bias.bin": bias, "input.bin": input_,
                "expected_output.bin": expected_output,
            },
        )
    else:
        print(
            "warning: no --approved-manifest given, skipping provenance verification "
            "(fine for local iteration, required before the first hardware bring-up run)",
            file=sys.stderr,
        )

    config_sha = sha256_hex((args.vector_dir / "config.json").read_bytes())
    seed = config.get("seed")
    has_seed = 1 if seed is not None else 0
    seed_value = int(seed) if seed is not None else 0

    args.output.parent.mkdir(parents=True, exist_ok=True)

    body = f"""/* Generated by scripts/generate_stage1_c_header.py from
 * {args.vector_dir.relative_to(REPO_ROOT)} -- do not edit by hand.
 *
 * §13.1 canonical stage-1 single-convolution test vector, embedded as byte arrays
 * because bare-metal firmware has no filesystem to load the .bin files from.
 *
 * Provenance (§9): config.json sha256 = {config_sha}
 */
#ifndef STAGE1_TEST_VECTOR_H
#define STAGE1_TEST_VECTOR_H

#include <stdint.h>

#define STAGE1_INPUT_HEIGHT  {config["input_height"]}
#define STAGE1_INPUT_WIDTH   {config["input_width"]}
#define STAGE1_IN_CHANNELS   {config["in_channels"]}
#define STAGE1_OUT_CHANNELS  {config["out_channels"]}
#define STAGE1_KERNEL_SIZE   {config["kernel_size"]}
#define STAGE1_STRIDE        {config["stride"]}
#define STAGE1_PADDING       {config["padding"]}
#define STAGE1_RELU_ENABLE   {1 if config["relu_enable"] else 0}
#define STAGE1_MULTIPLIER_M  {multiplier_m}
#define STAGE1_SHIFT_N       {shift_n}

#define STAGE1_WEIGHT_BYTES  {config["weight_bytes"]}
#define STAGE1_BIAS_BYTES    {config["bias_bytes"]}
#define STAGE1_INPUT_BYTES   {config["input_bytes"]}
#define STAGE1_OUTPUT_BYTES  {config["output_bytes"]}

#define STAGE1_VECTOR_CONFIG_SHA256 "{config_sha}"
#define STAGE1_VECTOR_HAS_SEED {has_seed}
#define STAGE1_VECTOR_SEED {seed_value} /* only meaningful when STAGE1_VECTOR_HAS_SEED == 1 */

{format_byte_array("stage1_weight", weight)}

{format_byte_array("stage1_bias", bias)}

{format_byte_array("stage1_input", input_)}

{format_byte_array("stage1_expected_output", expected_output)}

#endif /* STAGE1_TEST_VECTOR_H */
"""
    args.output.write_text(body)
    print(f"wrote {args.output} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
