#!/usr/bin/env python3
# Converts data/test_vectors/stage3_backbone/* (stem, block01..block09, gap, fc) into a C header
# of static byte arrays, mirroring generate_stage2_c_header.py / generate_stage3_gapfc_c_header.py
# (bare-metal firmware has no filesystem to load the .bin files from). Regenerate whenever
# scripts/generate_stage3_backbone_vectors.py produces new vectors.
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

NUM_BLOCKS = 9


def format_byte_array(name: str, data: bytes, values_per_line: int = 20) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(data), values_per_line):
        chunk = data[i : i + values_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def _load_conv(conv_dir: Path) -> dict:
    config = json.loads((conv_dir / "config.json").read_text())
    weight = (conv_dir / "weight.bin").read_bytes()
    bias = (conv_dir / "bias.bin").read_bytes()
    expected_output = (conv_dir / "expected_output.bin").read_bytes()
    assert len(weight) == config["weight_bytes"]
    assert len(bias) == config["bias_bytes"]
    assert len(expected_output) == config["output_bytes"]
    return {"config": config, "weight": weight, "bias": bias, "expected_output": expected_output}


def _conv_macros(prefix: str, cfg: dict) -> str:
    return f"""#define {prefix}_INPUT_HEIGHT   {cfg["input_height"]}
#define {prefix}_INPUT_WIDTH    {cfg["input_width"]}
#define {prefix}_IN_CHANNELS    {cfg["in_channels"]}
#define {prefix}_OUT_CHANNELS   {cfg["out_channels"]}
#define {prefix}_KERNEL_SIZE    {cfg["kernel_size"]}
#define {prefix}_STRIDE         {cfg["stride"]}
#define {prefix}_PADDING        {cfg["padding"]}
#define {prefix}_RELU_ENABLE    {1 if cfg["relu_enable"] else 0}
#define {prefix}_MULTIPLIER_M   {cfg["multiplier_m"]}
#define {prefix}_SHIFT_N        {cfg["shift_n"]}
#define {prefix}_WEIGHT_BYTES   {cfg["weight_bytes"]}
#define {prefix}_BIAS_BYTES     {cfg["bias_bytes"]}
#define {prefix}_OUTPUT_BYTES   {cfg["output_bytes"]}"""


def _conv_section(prefix: str, varname: str, conv: dict) -> str:
    return f"""{_conv_macros(prefix, conv["config"])}

{format_byte_array(f"{varname}_weight", conv["weight"])}

{format_byte_array(f"{varname}_bias", conv["bias"])}

{format_byte_array(f"{varname}_expected_output", conv["expected_output"])}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vector-root", type=Path, default=REPO_ROOT / "data" / "test_vectors")
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    vector_dir = args.vector_root / "stage3_backbone"
    output = args.output or (
        REPO_ROOT / "firmware" / "test" / "generated" / "stage3_backbone_test_vector.h"
    )

    chain_config = json.loads((vector_dir / "chain_config.json").read_text())
    if chain_config["num_blocks"] != NUM_BLOCKS:
        raise ValueError(f"expected {NUM_BLOCKS} blocks, chain_config.json has {chain_config['num_blocks']}")

    stem = _load_conv(vector_dir / "stem")
    input_x = (vector_dir / "stem" / "input.bin").read_bytes()
    assert len(input_x) == stem["config"]["input_bytes"]

    sections = [f"""/* Generated by scripts/generate_stage3_backbone_c_header.py from
 * {vector_dir.relative_to(REPO_ROOT)} -- do not edit by hand.
 *
 * Full ResNet-20 CIFAR backbone test vector (STAGE3_MASTER_ROADMAP.md §2.2): stem -> 9x
 * BasicBlock (stage1 3x identity/16ch, stage2 1x projection+2x identity/32ch, stage3 1x
 * projection+2x identity/64ch) -> OP_GLOBAL_AVG_POOL -> FC(=OP_CONV kernel=1) -> predicted class.
 * Each block's own conv1/conv2/[shortcut]/residual-add checkpoint is a separate accelerator
 * operation, exactly like the single-block stage-2 tests, just chained 9 times in a row.
 * Regenerate with scripts/generate_stage3_backbone_vectors.py after any model/seed change.
 */
#ifndef STAGE3_BACKBONE_TEST_VECTOR_H
#define STAGE3_BACKBONE_TEST_VECTOR_H

#include <stdint.h>

#define STAGE3_BACKBONE_NUM_BLOCKS {NUM_BLOCKS}
#define STAGE3_BACKBONE_NUM_VALID_CLASSES {chain_config["num_valid_classes"]}
#define STAGE3_BACKBONE_EXPECTED_PREDICTED_CLASS {chain_config["predicted_class"]}

{_conv_section("STAGE3_BACKBONE_STEM", "stage3_backbone_stem", stem)}
{format_byte_array("stage3_backbone_input_x", input_x)}
"""]

    for block_index in range(1, NUM_BLOCKS + 1):
        block_dir = vector_dir / f"block{block_index:02d}"
        block_prefix = f"STAGE3_BACKBONE_BLOCK{block_index:02d}"
        block_var = f"stage3_backbone_block{block_index:02d}"
        is_projection = (block_dir / "shortcut").is_dir()

        conv1 = _load_conv(block_dir / "conv1")
        conv2 = _load_conv(block_dir / "conv2")
        residual_config = json.loads((block_dir / "residual" / "residual_config.json").read_text())
        final_expected_output = (block_dir / "residual" / "final_expected_output.bin").read_bytes()

        block_section = [f"""/* block{block_index:02d}: {residual_config["shortcut_kind"]} shortcut, block scale={residual_config["block_scale"]:.6f} */
{_conv_section(f"{block_prefix}_CONV1", f"{block_var}_conv1", conv1)}
{_conv_section(f"{block_prefix}_CONV2", f"{block_var}_conv2", conv2)}"""]

        if is_projection:
            shortcut = _load_conv(block_dir / "shortcut")
            block_section.append(_conv_section(f"{block_prefix}_SHORTCUT", f"{block_var}_shortcut", shortcut))

        block_section.append(f"""#define {block_prefix}_RESIDUAL_RELU_ENABLE 1
{format_byte_array(f"{block_var}_expected_output", final_expected_output)}
""")
        sections.append("\n".join(block_section))

    gap_config = json.loads((vector_dir / "gap" / "config.json").read_text())
    gap_expected_output = (vector_dir / "gap" / "expected_output.bin").read_bytes()
    assert len(gap_expected_output) == gap_config["output_bytes"]

    fc = _load_conv(vector_dir / "fc")
    fc_input_check = (vector_dir / "fc" / "input.bin").read_bytes()
    if fc_input_check != gap_expected_output:
        raise ValueError(
            "fc/input.bin does not match gap/expected_output.bin -- vectors are stale, "
            "regenerate with scripts/generate_stage3_backbone_vectors.py"
        )

    sections.append(f"""#define STAGE3_BACKBONE_GAP_INPUT_HEIGHT  {gap_config["input_height"]}
#define STAGE3_BACKBONE_GAP_INPUT_WIDTH   {gap_config["input_width"]}
#define STAGE3_BACKBONE_GAP_IN_CHANNELS   {gap_config["in_channels"]}
#define STAGE3_BACKBONE_GAP_OUT_CHANNELS  {gap_config["out_channels"]}
#define STAGE3_BACKBONE_GAP_MULTIPLIER_M  {gap_config["multiplier_m"]}
#define STAGE3_BACKBONE_GAP_SHIFT_N       {gap_config["shift_n"]}
#define STAGE3_BACKBONE_GAP_INPUT_BYTES   {gap_config["input_bytes"]}
#define STAGE3_BACKBONE_GAP_OUTPUT_BYTES  {gap_config["output_bytes"]}

{format_byte_array("stage3_backbone_gap_expected_output", gap_expected_output)}

{_conv_section("STAGE3_BACKBONE_FC", "stage3_backbone_fc", fc)}
#endif /* STAGE3_BACKBONE_TEST_VECTOR_H */
""")

    body = "\n".join(sections)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(body)
    print(f"wrote {output} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
